// ============================================================
// Build script - 生成 Prisma 客户端 + Windows Manifest + 复制 ImageMagick 资源
// ============================================================

use std::fs;
use std::path::Path;

fn main() {
    println!("cargo:rerun-if-changed=../../prisma/schema.prisma");
    println!("cargo:warning=Prisma client will be generated by prisma_client_rust::generate! macro");

    // Tauri 构建
    tauri_build::build();

    // 在开发环境中复制 ImageMagick 资源文件
    // Tauri 的 bundle.resources 配置仅在生产打包时生效
    copy_imagemagick_resources();
}

fn copy_imagemagick_resources() {
    // 获取输出目录
    let out_dir = match std::env::var("OUT_DIR") {
        Ok(dir) => dir,
        Err(_) => return,
    };

    let target_dir = match Path::new(&out_dir).ancestors().nth(3) {
        Some(dir) => dir,
        None => return,
    };

    let profile = std::env::var("PROFILE").unwrap_or_default(); // debug or release

    // 仅在开发构建时复制（生产构建由 Tauri bundle 处理）
    if profile != "debug" {
        return;
    }

    let resources_dir = target_dir.join(profile).join("resources");
    let imagemagick_target = resources_dir.join("imagemagick");
    let imagemagick_source = Path::new("resources/imagemagick");

    // 检查源目录是否存在
    if !imagemagick_source.exists() {
        return;
    }

    println!("[build.rs] 开发构建：复制 ImageMagick 资源...");

    // 确保目标目录存在
    if let Err(e) = fs::create_dir_all(&imagemagick_target) {
        println!("[build.rs] 警告: 创建目录失败: {}", e);
        return;
    }

    // 复制所有文件和目录
    if let Err(e) = copy_dir_recursive(imagemagick_source, &imagemagick_target) {
        println!("[build.rs] 警告: 复制资源失败: {}", e);
        return;
    }

    println!("[build.rs] ImageMagick 资源已复制到: {:?}", imagemagick_target);
}

fn copy_dir_recursive(source: &Path, target: &Path) -> std::io::Result<()> {
    for entry in fs::read_dir(source)? {
        let entry = entry?;
        let ty = entry.file_type()?;
        let source_path = entry.path();
        let target_path = target.join(entry.file_name());

        if ty.is_dir() {
            fs::create_dir_all(&target_path)?;
            copy_dir_recursive(&source_path, &target_path)?;
        } else {
            fs::copy(&source_path, &target_path)?;
        }
    }
    Ok(())
}
