// ============================================================
// Build script - 生成 Prisma 客户端 + Windows Manifest
// ============================================================

fn main() {
    println!("cargo:rerun-if-changed=../../prisma/schema.prisma");
    println!("cargo:warning=Prisma client will be generated by prisma_client_rust::generate! macro");

    // Tauri 构建
    tauri_build::build()
}
